// 13-items.js
//
// Classifies an item `type` string (an outfit, a backpack, a gun, ...) into
// its category, as declared by the game's own definitions. Two things read
// it: 10-ctx.js finds a player's netData by looking for the object that
// carries both an outfit and a backpack, and Anti-Cosmetics (21-cosmetics.js)
// uses it as the fallback for "is this string an outfit" in the frames
// before the live def registry (MOUSE.gameDefs) has resolved.
//
// ITEM_CATEGORY below was built by parsing every shared/defs/gameObjects/*.ts
// file in the survev repo (gearDefs, throwableDefs, perkDefs, xpDefs,
// outfitDefs, gunDefs, meleeDefs) and reading each item's declared `type`
// field, resolving skins through their base item where the skin itself has
// no explicit type. Hand-maintained; update it by hand after a game update
// adds or renames items - `bun tools/check-item-table.ts` diffs it against
// the pinned survev checkout and names every item that has drifted. Run it
// whenever MOUSE.TARGET moves: a missing entry fails silently rather than
// loudly.

(function () {
    "use strict";

    /** @type {any} */
    const w = window;
    const MOUSE = w.__MOUSE;

    const ITEM_CATEGORY = {
        // ammo (9)
        "12gauge": "ammo",
        "308sub": "ammo",
        "45acp": "ammo",
        "50AE": "ammo",
        "556mm": "ammo",
        "762mm": "ammo",
        "9mm": "ammo",
        "flare": "ammo",
        "potato_ammo": "ammo",
        // heal (2)
        "bandage": "heal",
        "healthkit": "heal",
        // boost (2)
        "painkiller": "boost",
        "soda": "boost",
        // chest (4)
        "chest01": "chest",
        "chest02": "chest",
        "chest03": "chest",
        "chest04": "chest",
        // helmet (20)
        "helmet01": "helmet",
        "helmet02": "helmet",
        "helmet03": "helmet",
        "helmet03_bugler": "helmet",
        "helmet03_forest": "helmet",
        "helmet03_grenadier": "helmet",
        "helmet03_leader": "helmet",
        "helmet03_lt": "helmet",
        "helmet03_lt_aged": "helmet",
        "helmet03_marksman": "helmet",
        "helmet03_moon": "helmet",
        "helmet03_potato": "helmet",
        "helmet03_recon": "helmet",
        "helmet04": "helmet",
        "helmet04_captain": "helmet",
        "helmet04_classless": "helmet",
        "helmet04_last_man_blue": "helmet",
        "helmet04_last_man_red": "helmet",
        "helmet04_leader": "helmet",
        "helmet04_medic": "helmet",
        // backpack (6)
        "backpack00": "backpack",
        "backpack01": "backpack",
        "backpack02": "backpack",
        "backpack03": "backpack",
        "backpack04": "backpack",
        "backpack04_cloud": "backpack",
        // scope (5)
        "15xscope": "scope",
        "1xscope": "scope",
        "2xscope": "scope",
        "4xscope": "scope",
        "8xscope": "scope",
        // throwable (16)
        "bomb_iron": "throwable",
        "coconut": "throwable",
        "frag": "throwable",
        "martyr_nade": "throwable",
        "mirv": "throwable",
        "mirv_mini": "throwable",
        "potato": "throwable",
        "potato_cannonball": "throwable",
        "potato_heavy": "throwable",
        "potato_lmgshot": "throwable",
        "potato_smgshot": "throwable",
        "smoke": "throwable",
        "snowball": "throwable",
        "snowball_heavy": "throwable",
        "strobe": "throwable",
        "tomato": "throwable",
        // outfit (90)
        "outfitAirdrop": "outfit",
        "outfitAqua": "outfit",
        "outfitAssault": "outfit",
        "outfitAurora": "outfit",
        "outfitBarrel": "outfit",
        "outfitBase": "outfit",
        "outfitBeachCamo": "outfit",
        "outfitBlackIce": "outfit",
        "outfitBlueLeader": "outfit",
        "outfitBlueLeaderAged": "outfit",
        "outfitBush": "outfit",
        "outfitBushRiver": "outfit",
        "outfitCamo": "outfit",
        "outfitCarbonFiber": "outfit",
        "outfitCasanova": "outfit",
        "outfitChameleon": "outfit",
        "outfitChrys": "outfit",
        "outfitClassless": "outfit",
        "outfitCobaltShell": "outfit",
        "outfitCoconut": "outfit",
        "outfitCoral": "outfit",
        "outfitCowz": "outfit",
        "outfitCrab": "outfit",
        "outfitCrate": "outfit",
        "outfitDarkGloves": "outfit",
        "outfitDarkShirt": "outfit",
        "outfitDemo": "outfit",
        "outfitDesertCamo": "outfit",
        "outfitDev": "outfit",
        "outfitElf": "outfit",
        "outfitEvent": "outfit",
        "outfitFahrenheit": "outfit",
        "outfitFragtastic": "outfit",
        "outfitGD": "outfit",
        "outfitGhillie": "outfit",
        "outfitGold": "outfit",
        "outfitHalloweenTree": "outfit",
        "outfitHeaven": "outfit",
        "outfitImperial": "outfit",
        "outfitIslander": "outfit",
        "outfitJester": "outfit",
        "outfitKeyLime": "outfit",
        "outfitKhaki": "outfit",
        "outfitLeafPile": "outfit",
        "outfitLumber": "outfit",
        "outfitMaintainer": "outfit",
        "outfitMedic": "outfit",
        "outfitMeteor": "outfit",
        "outfitMod": "outfit",
        "outfitNoir": "outfit",
        "outfitOven": "outfit",
        "outfitParma": "outfit",
        "outfitParmaPrestige": "outfit",
        "outfitParrotfish": "outfit",
        "outfitPastel": "outfit",
        "outfitPineapple": "outfit",
        "outfitPotatoskin": "outfit",
        "outfitPrisoner": "outfit",
        "outfitPumpkin": "outfit",
        "outfitRain": "outfit",
        "outfitRed": "outfit",
        "outfitRedLeader": "outfit",
        "outfitRedLeaderAged": "outfit",
        "outfitRefrigerator": "outfit",
        "outfitRoyalFortune": "outfit",
        "outfitScout": "outfit",
        "outfitSniper": "outfit",
        "outfitSnow": "outfit",
        "outfitSoviet": "outfit",
        "outfitSpetsnaz": "outfit",
        "outfitSpringTree": "outfit",
        "outfitStone": "outfit",
        "outfitStump": "outfit",
        "outfitStumpAxe": "outfit",
        "outfitTable": "outfit",
        "outfitTank": "outfit",
        "outfitTarkhany": "outfit",
        "outfitToilet": "outfit",
        "outfitTreeSpooky": "outfit",
        "outfitTurkey": "outfit",
        "outfitVending": "outfit",
        "outfitVerde": "outfit",
        "outfitWaterElem": "outfit",
        "outfitWave": "outfit",
        "outfitWheat": "outfit",
        "outfitWhite": "outfit",
        "outfitWoodBarrel": "outfit",
        "outfitWoodland": "outfit",
        "outfitWoodpile": "outfit",
        "outfitWoodsCloak": "outfit",
        // perk (48)
        "amped_explosives": "perk",
        "aoe_heal": "perk",
        "ap_rounds": "perk",
        "assume_leadership": "perk",
        "bonus_45": "perk",
        "bonus_9mm": "perk",
        "bonus_assault": "perk",
        "broken_arrow": "perk",
        "chambered": "perk",
        "combat_stims": "perk",
        "endless_ammo": "perk",
        "explosive": "perk",
        "fabricate": "perk",
        "field_medic": "perk",
        "final_bugle": "perk",
        "firepower": "perk",
        "flak_jacket": "perk",
        "gotw": "perk",
        "halloween_mystery": "perk",
        "high_velocity": "perk",
        "hunted": "perk",
        "inspiration": "perk",
        "leadership": "perk",
        "lifeline": "perk",
        "martyrdom": "perk",
        "pirate": "perk",
        "rare_potato": "perk",
        "scavenger": "perk",
        "scavenger_adv": "perk",
        "self_revive": "perk",
        "small_arms": "perk",
        "splinter": "perk",
        "steelskin": "perk",
        "takedown": "perk",
        "targeting": "perk",
        "treat_12g": "perk",
        "treat_556": "perk",
        "treat_762": "perk",
        "treat_9mm": "perk",
        "treat_super": "perk",
        "tree_climbing": "perk",
        "trick_chatty": "perk",
        "trick_drain": "perk",
        "trick_m9": "perk",
        "trick_nothing": "perk",
        "trick_size": "perk",
        "turkey_shoot": "perk",
        "windwalk": "perk",
        // xp (14)
        "xp_10": "xp",
        "xp_100": "xp",
        "xp_25": "xp",
        "xp_bone": "xp",
        "xp_book_greene": "xp",
        "xp_book_kuga": "xp",
        "xp_book_nevelskoy": "xp",
        "xp_book_parma": "xp",
        "xp_book_rinzo": "xp",
        "xp_book_tallow": "xp",
        "xp_compass": "xp",
        "xp_donut": "xp",
        "xp_glasses": "xp",
        "xp_stump": "xp",
        // gun (74)
        "ak47": "gun",
        "an94": "gun",
        "ash12": "gun",
        "awc": "gun",
        "awc_winter": "gun",
        "bar": "gun",
        "barrett": "gun",
        "blr": "gun",
        "bugle": "gun",
        "colt45": "gun",
        "colt45_dual": "gun",
        "deagle": "gun",
        "deagle_dual": "gun",
        "dp28": "gun",
        "famas": "gun",
        "flare_gun": "gun",
        "flare_gun_dual": "gun",
        "garand": "gun",
        "glock": "gun",
        "glock_dual": "gun",
        "groza": "gun",
        "grozas": "gun",
        "hk416": "gun",
        "imbel": "gun",
        "l86": "gun",
        "m1014": "gun",
        "m1100": "gun",
        "m1911": "gun",
        "m1911_dual": "gun",
        "m1a1": "gun",
        "m249": "gun",
        "m39": "gun",
        "m4a1": "gun",
        "m870": "gun",
        "m9": "gun",
        "m93r": "gun",
        "m93r_dual": "gun",
        "m9_cursed": "gun",
        "m9_dual": "gun",
        "mac10": "gun",
        "mk12": "gun",
        "mkg45": "gun",
        "model94": "gun",
        "mosin": "gun",
        "mp220": "gun",
        "mp5": "gun",
        "ot38": "gun",
        "ot38_dual": "gun",
        "ots38": "gun",
        "ots38_dual": "gun",
        "p30l": "gun",
        "p30l_dual": "gun",
        "pkp": "gun",
        "potato_cannon": "gun",
        "potato_lmg": "gun",
        "potato_smg": "gun",
        "qbb97": "gun",
        "saiga": "gun",
        "scar": "gun",
        "scarssr": "gun",
        "scorpion": "gun",
        "scout_elite": "gun",
        "spas12": "gun",
        "spas16": "gun",
        "sv98": "gun",
        "sv98_winter": "gun",
        "svd": "gun",
        "svd_winter": "gun",
        "sw500": "gun",
        "ump9": "gun",
        "usas": "gun",
        "vector": "gun",
        "vector45": "gun",
        "vss": "gun",
        // melee (47)
        "bayonet": "melee",
        "bayonet_rugged": "melee",
        "bayonet_woodland": "melee",
        "bonesaw_healer": "melee",
        "bonesaw_rusted": "melee",
        "bowie": "melee",
        "bowie_frontier": "melee",
        "bowie_vintage": "melee",
        "crowbar": "melee",
        "crowbar_recon": "melee",
        "crowbar_scout": "melee",
        "cutlass": "melee",
        "cutlass_gold": "melee",
        "fireaxe": "melee",
        "fists": "melee",
        "hook": "melee",
        "huntsman": "melee",
        "huntsman_burnished": "melee",
        "huntsman_rugged": "melee",
        "iceaxe": "melee",
        "karambit": "melee",
        "karambit_borealis": "melee",
        "karambit_drowned": "melee",
        "karambit_prismatic": "melee",
        "karambit_rugged": "melee",
        "katana": "melee",
        "katana_demo": "melee",
        "katana_orchid": "melee",
        "katana_rusted": "melee",
        "knuckles": "melee",
        "knuckles_heroic": "melee",
        "knuckles_rusted": "melee",
        "kukri_sniper": "melee",
        "kukri_trad": "melee",
        "machete": "melee",
        "machete_taiga": "melee",
        "naginata": "melee",
        "naginata_daemon": "melee",
        "pan": "melee",
        "saw": "melee",
        "sledgehammer": "melee",
        "spade": "melee",
        "spade_assault": "melee",
        "stonehammer": "melee",
        "warhammer_tank": "melee",
        "woodaxe": "melee",
        "woodaxe_bloody": "melee",
    };

    MOUSE.items = {
        ITEM_CATEGORY,
    };
    MOUSE.log("item table loaded (" + Object.keys(ITEM_CATEGORY).length + " known items)");
})();
