// Verbatim gunDefs entries from leia-uwu/survev @ 6ab329ee46c1e2a2b42aee56bee1e34b73913edd
// v0.1.1 (2025-06-06) - shared/defs/gameObjects/gunDefs.ts

// ---- an94  (AN-94) - sprite changed in v0.1.2
    an94: {
        name: "AN-94",
        type: "gun",
        quality: 1,
        fireMode: "burst",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 90,
        maxClip: 45,
        maxReload: 45,
        extendedClip: 60,
        extendedReload: 60,
        reloadTime: 2.35,
        fireDelay: 0.24,
        burstDelay: 0.025,
        switchDelay: 0.75,
        barrelLength: 3.25,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 4,
        shotSpread: 1.5,
        bulletCount: 1,
        burstCount: 2,
        burstSounds: 1,
        bulletType: "bullet_an94",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-an94.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.46 },
            tint: 0x2d2d2d,
            leftHandOffset: { x: 2.85, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "an94_01",
            reload: "an94_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "an94_switch_01",
        },
    }

// ---- bar  (BAR M1918) - sprite changed in v0.1.2
    bar: {
        name: "BAR M1918",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 80,
        maxClip: 20,
        maxReload: 20,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 2.7,
        fireDelay: 0.12,
        switchDelay: 0.75,
        barrelLength: 3.7,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 8,
        shotSpread: 2,
        bulletCount: 1,
        bulletType: "bullet_bar",
        headshotMult: 2,
        speed: { equip: 0, attack: -1.5 },
        lootImg: {
            sprite: "loot-weapon-bar.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0x4d4c52,
            leftHandOffset: { x: 6.8, y: 0 },
            recoil: 1.4,
        },
        particle: { shellScale: 1, shellOffset: 0.6 },
        sound: {
            shoot: "bar_01",
            reload: "bar_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "bar_switch_01",
        },
    }

// ---- dp28  (DP-28) - sprite changed in v0.1.2
    dp28: {
        name: "DP-28",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 120,
        maxClip: 60,
        maxReload: 60,
        extendedClip: 80,
        extendedReload: 80,
        reloadTime: 3.3,
        fireDelay: 0.115,
        switchDelay: 0.75,
        barrelLength: 3.75,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 9,
        shotSpread: 2,
        bulletCount: 1,
        bulletType: "bullet_dp28",
        headshotMult: 2,
        speed: { equip: 0, attack: -2 },
        lootImg: {
            sprite: "loot-weapon-dp28.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.53 },
            tint: 0x1a1a1a,
            leftHandOffset: { x: 8.4, y: 0 },
            recoil: 1.33,
            magImg: {
                sprite: "gun-dp28-top-01.img",
                pos: { x: 0, y: -22.5 },
                top: true,
            },
        },
        particle: { shellScale: 1, shellOffset: 0.6 },
        sound: {
            shoot: "dp28_01",
            reload: "dp28_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "dp28_switch_01",
        },
    }

// ---- flare_gun  (Flare Gun) - sprite changed in v0.1.2
    flare_gun: {
        name: "Flare Gun",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "flare",
        dualWieldType: "flare_gun_dual",
        pistol: true,
        outsideOnly: true,
        ammoSpawnCount: 1,
        ignoreEndlessAmmo: true,
        maxClip: 1,
        maxReload: 1,
        extendedClip: 1,
        extendedReload: 1,
        reloadTime: 2,
        fireDelay: 0.4,
        switchDelay: 0.3,
        barrelLength: 2,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.25,
        bulletCount: 1,
        bulletType: "bullet_flare",
        noSplinter: true,
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-flare-gun.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.4625 },
            tint: 0xff5400,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "flare_gun_01",
            reload: "flare_gun_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "gun_switch_01",
        },
    }

// ---- m1014  (M1014) - sprite changed in v0.1.2
    m1014: {
        name: "M1014",
        type: "gun",
        quality: 1,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "12gauge",
        ammoSpawnCount: 16,
        maxClip: 8,
        maxReload: 1,
        extendedClip: 10,
        extendedReload: 1,
        reloadTime: 0.52,
        fireDelay: 0.4,
        switchDelay: 0.75,
        barrelLength: 3.2,
        barrelOffset: 0,
        recoilTime: 0.5,
        moveSpread: 4,
        shotSpread: 4,
        bulletCount: 1,
        jitter: 0.2,
        bulletType: "bullet_slug",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-m1014.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.44 },
            tint: 0x565038,
            leftHandOffset: { x: 4.8, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "m1014_01",
            reload: "m1014_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "m1014_deploy_01",
        },
    }

// ---- qbb97  (QBB-97) - sprite changed in v0.1.2
    qbb97: {
        name: "QBB-97",
        type: "gun",
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "556mm",
        ammoSpawnCount: 150,
        maxClip: 75,
        maxReload: 75,
        extendedClip: 95,
        extendedReload: 95,
        reloadTime: 3.9,
        fireDelay: 0.1,
        switchDelay: 0.75,
        barrelLength: 3.1,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 0.5,
        shotSpread: 4,
        bulletCount: 1,
        bulletType: "bullet_qbb97",
        headshotMult: 2,
        speed: { equip: 0, attack: -2 },
        lootImg: {
            sprite: "loot-weapon-qbb97.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.425 },
            tint: 0x1e1e1e,
            leftHandOffset: { x: 8.4, y: 0 },
            recoil: 1.33,
            magImg: {
                sprite: "gun-qbb97-bot-01.img",
                pos: { x: -1.5, y: -14.25 },
            },
        },
        particle: { shellScale: 1, shellOffset: 0.5875 },
        sound: {
            shoot: "qbb97_01",
            reload: "qbb97_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "qbb97_switch_01",
        },
    }

// ---- flare_gun_dual  (Dual Flare Gun) - sprite changed in v0.1.2
    flare_gun_dual: {
        name: "Dual Flare Gun",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "flare",
        isDual: true,
        pistol: true,
        outsideOnly: true,
        ammoSpawnCount: 2,
        ignoreEndlessAmmo: true,
        maxClip: 2,
        maxReload: 2,
        extendedClip: 2,
        extendedReload: 2,
        reloadTime: 3.5,
        fireDelay: 0.3,
        switchDelay: 0.3,
        barrelLength: 2,
        barrelOffset: 0,
        dualOffset: 0.6,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.25,
        bulletCount: 1,
        bulletType: "bullet_flare",
        noSplinter: true,
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-flare-gun-dual.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.4625 },
            tint: 0xff5400,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "flare_gun_01",
            reload: "flare_gun_reload_02",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "gun_switch_01",
        },
    }

// ---- colt45  (Peacemaker) - sprite changed in v0.1.31
    colt45: {
        name: "Peacemaker",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "reload",
        ammo: "45acp",
        ammoSpawnCount: 48,
        dualWieldType: "colt45_dual",
        pistol: true,
        maxClip: 6,
        maxReload: 6,
        extendedClip: 6,
        extendedReload: 6,
        reloadTime: 3,
        fireDelay: 0.12,
        switchDelay: 0.3,
        barrelLength: 2.26,
        barrelOffset: 0,
        recoilTime: 0.35,
        moveSpread: 3,
        shotSpread: 16,
        bulletCount: 1,
        bulletType: "bullet_colt45",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-colt45.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0xc4c4c4,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1.2, shellOffset: 0.225 },
        sound: {
            shoot: "colt45_01",
            reload: "colt45_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "colt45_switch_01",
        },
    }

// ---- m1100  (M1100) - sprite changed in v0.1.31
    m1100: {
        name: "M1100",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "12gauge",
        ammoSpawnCount: 12,
        maxClip: 4,
        maxReload: 1,
        extendedClip: 8,
        extendedReload: 1,
        reloadTime: 0.7,
        fireDelay: 0.3,
        switchDelay: 0.9,
        barrelLength: 3.15,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 2,
        shotSpread: 25,
        bulletCount: 18,
        jitter: 1,
        bulletType: "bullet_birdshot",
        headshotMult: 1.5,
        lootImg: {
            sprite: "loot-weapon-m1100.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        speed: { equip: 0, attack: 0 },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.435 },
            tint: 0x2e442e,
            leftHandOffset: { x: 7, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "m1100_01",
            reload: "m1100_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "m1100_deploy_01",
        },
    }

// ---- model94  (Model 94) - sprite changed in v0.1.31
    model94: {
        name: "Model 94",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "45acp",
        ammoSpawnCount: 64,
        maxClip: 8,
        maxReload: 1,
        extendedClip: 8,
        extendedReload: 1,
        reloadTime: 0.5,
        fireDelay: 0.7,
        switchDelay: 1,
        pullDelay: 1,
        barrelLength: 3.7,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.5,
        bulletCount: 1,
        bulletType: "bullet_model94",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-model94.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.5175 },
            tint: 0xa06120,
            leftHandOffset: { x: 3.2, y: 0 },
            recoil: 2.33,
        },
        particle: { shellScale: 1.4, shellOffset: 0.6 },
        sound: {
            shoot: "model94_01",
            reload: "model94_reload_01",
            cycle: "model94_cycle_01",
            pull: "model94_cycle_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "model94_cycle_01",
        },
    }

// ---- mosin  (Mosin-Nagant) - sprite changed in v0.1.31
    mosin: {
        name: "Mosin-Nagant",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "762mm",
        aimDelay: true,
        ammoSpawnCount: 20,
        maxClip: 5,
        maxReload: 1,
        maxReloadAlt: 5,
        extendedClip: 5,
        extendedReload: 1,
        extendedReloadAlt: 5,
        reloadTime: 0.9,
        reloadTimeAlt: 3,
        fireDelay: 1.75,
        switchDelay: 1,
        pullDelay: 1,
        barrelLength: 3.75,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1,
        bulletCount: 1,
        bulletType: "bullet_mosin",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-mosin.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0x331a00,
            leftHandOffset: { x: 2.8, y: 0 },
            recoil: 2.33,
        },
        particle: { shellScale: 1.6, shellOffset: 0.6 },
        sound: {
            shoot: "mosin_01",
            reload: "mosin_reload_01",
            reloadAlt: "mosin_reload_02",
            cycle: "mosin_cycle_01",
            pull: "mosin_pull_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "mosin_cycle_01",
        },
    }

// ---- scar  (SCAR-H) - sprite changed in v0.1.31
    scar: {
        name: "SCAR-H",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 80,
        maxClip: 20,
        maxReload: 20,
        extendedClip: 30,
        extendedReload: 30,
        reloadTime: 2.7,
        fireDelay: 0.09,
        switchDelay: 0.75,
        barrelLength: 3.15,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 5,
        shotSpread: 2,
        bulletCount: 1,
        bulletType: "bullet_scar",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-scar.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.435 },
            tint: 0x9b7b48,
            leftHandOffset: { x: 2.8, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "scar_01",
            reload: "scar_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "scar_switch_01",
        },
    }

// ---- scout_elite  (Scout Elite) - sprite changed in v0.1.31
    scout_elite: {
        name: "Scout Elite",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "556mm",
        aimDelay: true,
        ammoSpawnCount: 20,
        maxClip: 5,
        maxReload: 5,
        extendedClip: 10,
        extendedReload: 10,
        reloadTime: 2.6,
        fireDelay: 1,
        switchDelay: 1,
        pullDelay: 1,
        barrelLength: 3.5,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 1,
        shotSpread: 1,
        bulletCount: 1,
        bulletType: "bullet_scout",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 5 },
        lootImg: {
            sprite: "loot-weapon-scout.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0x32363b,
            leftHandOffset: { x: 2.8, y: 0 },
            recoil: 2.33,
        },
        particle: { shellScale: 1.6, shellOffset: 0.6 },
        sound: {
            shoot: "scout_01",
            reload: "scout_reload_01",
            cycle: "scout_cycle_01",
            pull: "scout_pull_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "scout_cycle_01",
        },
    }

// ---- vector  (Vector) - sprite changed in v0.1.31
    vector: {
        name: "Vector",
        type: "gun",
        quality: 1,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 99,
        maxClip: 33,
        maxReload: 33,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 1.6,
        fireDelay: 0.038,
        switchDelay: 0.75,
        barrelLength: 2.5,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 4.5,
        shotSpread: 2.5,
        bulletCount: 1,
        bulletType: "bullet_vector",
        bulletTypeBonus: "bullet_vector_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-vector.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.5 },
            tint: 0x897960,
            leftHandOffset: { x: 7, y: 0 },
            recoil: 0.89,
        },
        particle: { shellScale: 1, shellOffset: 0.4 },
        sound: {
            shoot: "vector_01",
            reload: "vector_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "vector_switch_01",
        },
    }

// ---- vector45  (Vector) - sprite changed in v0.1.31
    vector45: {
        name: "Vector",
        type: "gun",
        quality: 1,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "45acp",
        ammoSpawnCount: 75,
        maxClip: 25,
        maxReload: 25,
        extendedClip: 32,
        extendedReload: 32,
        reloadTime: 1.6,
        fireDelay: 0.044,
        switchDelay: 0.75,
        barrelLength: 2.5,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 6.5,
        shotSpread: 4.5,
        bulletCount: 1,
        bulletType: "bullet_vector45",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-vector45.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.5 },
            tint: 0x897960,
            leftHandOffset: { x: 7, y: 0 },
            recoil: 0.89,
        },
        particle: { shellScale: 1.2, shellOffset: 0.4 },
        sound: {
            shoot: "vector_02",
            reload: "vector_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "vector_switch_01",
        },
    }

// ---- colt45_dual  (Dual Peacemaker) - sprite changed in v0.1.31
    colt45_dual: {
        name: "Dual Peacemaker",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "reload",
        ammo: "45acp",
        ammoSpawnCount: 48,
        isDual: true,
        pistol: true,
        maxClip: 12,
        maxReload: 12,
        extendedClip: 12,
        extendedReload: 12,
        reloadTime: 5.1,
        fireDelay: 0.13,
        switchDelay: 0.3,
        barrelLength: 2.26,
        barrelOffset: 0,
        dualOffset: 0.6,
        recoilTime: 0.35,
        moveSpread: 3,
        shotSpread: 16,
        bulletCount: 1,
        bulletType: "bullet_colt45",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-colt45-dual.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0xc4c4c4,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1.2, shellOffset: 0.225 },
        sound: {
            shoot: "colt45_01",
            reload: "colt45_reload_02",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "colt45_switch_01",
        },
    }

// ---- awc  (AWM-S) - sprite changed in v0.2.0
    awc: {
        name: "AWM-S",
        type: "gun",
        quality: 1,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "308sub",
        aimDelay: true,
        ammoSpawnCount: 20,
        maxClip: 5,
        maxReload: 5,
        extendedClip: 7,
        extendedReload: 7,
        reloadTime: 3.6,
        fireDelay: 1.5,
        switchDelay: 1,
        pullDelay: 1.4,
        barrelLength: 3.8,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 4,
        shotSpread: 0.5,
        bulletCount: 1,
        bulletType: "bullet_awc",
        headshotMult: 1,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-awc.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-awc-01.img",
            scale: { x: 0.5, y: 0.5 },
            tint: 0xffffff,
            leftHandOffset: { x: 11, y: 0 },
            recoil: 2.66,
        },
        particle: { shellScale: 1.5, shellOffset: 0.6 },
        sound: {
            shoot: "awc_01",
            reload: "awc_reload_01",
            cycle: "awc_cycle_01",
            pull: "awc_pull_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "awc_cycle_01",
            fallOff: 3,
        },
    }

// ---- l86  (L86A2) - sprite changed in v0.2.0
    l86: {
        name: "L86A2",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "556mm",
        ammoSpawnCount: 90,
        maxClip: 30,
        maxReload: 30,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 2.9,
        fireDelay: 0.19,
        switchDelay: 0.75,
        barrelLength: 3.25,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3.5,
        shotSpread: 1,
        bulletCount: 1,
        bulletType: "bullet_l86",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-l86.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.46 },
            tint: 0xdcc8a7,
            leftHandOffset: { x: -3, y: 0 },
            recoil: 1.66,
        },
        particle: { shellScale: 1.3, shellOffset: 0.55 },
        sound: {
            shoot: "l86_01",
            reload: "l86_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "l86_switch_01",
        },
    }

// ---- sv98  (SV-98) - sprite changed in v0.2.0
    sv98: {
        name: "SV-98",
        type: "gun",
        quality: 1,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "762mm",
        aimDelay: true,
        ammoSpawnCount: 30,
        maxClip: 10,
        maxReload: 10,
        extendedClip: 15,
        extendedReload: 15,
        reloadTime: 2.7,
        fireDelay: 1.5,
        switchDelay: 1,
        pullDelay: 0.8,
        barrelLength: 3.5,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 2.5,
        shotSpread: 1,
        bulletCount: 1,
        bulletType: "bullet_sv98",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-sv98.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.4925 },
            tint: 0x658947,
            leftHandOffset: { x: 2.8, y: 0 },
            recoil: 2.33,
        },
        particle: { shellScale: 1.6, shellOffset: 0.6 },
        sound: {
            shoot: "sv98_01",
            reload: "sv98_reload_01",
            cycle: "sv98_cycle_01",
            pull: "sv98_pull_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "sv98_cycle_01",
        },
    }

// ---- svd  (SVD-63) - sprite changed in v0.2.0
    svd: {
        name: "SVD-63",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 60,
        maxClip: 10,
        maxReload: 10,
        extendedClip: 20,
        extendedReload: 20,
        reloadTime: 2.5,
        fireDelay: 0.25,
        switchDelay: 0.75,
        barrelLength: 4,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 4.5,
        shotSpread: 1,
        bulletCount: 1,
        bulletType: "bullet_svd",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-svd.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.56 },
            tint: 0x1c1c1c,
            leftHandOffset: { x: 8, y: 0 },
            recoil: 2,
        },
        particle: { shellScale: 1.3, shellOffset: 0.575 },
        sound: {
            shoot: "svd_01",
            reload: "svd_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "svd_switch_01",
        },
    }

// ---- blr  (BLR 81) - sprite changed in v0.2.1
    blr: {
        name: "BLR 81",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "762mm",
        ammoSpawnCount: 30,
        maxClip: 3,
        maxReload: 3,
        extendedClip: 5,
        extendedReload: 5,
        reloadTime: 1.7,
        fireDelay: 0.8,
        switchDelay: 1,
        pullDelay: 1,
        barrelLength: 3.8,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.5,
        bulletCount: 1,
        bulletType: "bullet_blr",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-blr.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.53 },
            tint: 0x472706,
            leftHandOffset: { x: 6.4, y: 0 },
            recoil: 2.75,
        },
        particle: { shellScale: 1.4, shellOffset: 0.6 },
        sound: {
            shoot: "blr_01",
            reload: "blr_reload_01",
            cycle: "blr_cycle_01",
            pull: "blr_cycle_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "blr_cycle_01",
        },
    }

// ---- mkg45  (Mk45G) - sprite changed in v0.2.1
    mkg45: {
        name: "Mk45G",
        type: "gun",
        quality: 1,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "45acp",
        ammoSpawnCount: 52,
        maxClip: 13,
        maxReload: 13,
        extendedClip: 26,
        extendedReload: 26,
        reloadTime: 2.1,
        fireDelay: 0.17,
        switchDelay: 0.75,
        barrelLength: 3.3,
        barrelOffset: 0,
        recoilTime: 0.2,
        moveSpread: 7.5,
        shotSpread: 3.5,
        bulletCount: 1,
        bulletType: "bullet_mkg45",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-mkg45.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.47 },
            tint: 0x353535,
            leftHandOffset: { x: 4.2, y: 0 },
            recoil: 1.66,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "mkg45_01",
            reload: "mkg45_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_02",
            deploy: "mkg45_switch_01",
        },
    }

// ---- glock  (G18C) - icon changed in v0.2.2
    glock: {
        name: "G18C",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 51,
        dualWieldType: "glock_dual",
        pistol: true,
        maxClip: 17,
        maxReload: 17,
        extendedClip: 31,
        extendedReload: 31,
        reloadTime: 1.95,
        fireDelay: 0.06,
        switchDelay: 0.25,
        barrelLength: 2.2,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 10,
        shotSpread: 12,
        bulletCount: 1,
        bulletType: "bullet_glock",
        bulletTypeBonus: "bullet_glock_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-glock.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.49 },
            tint: 0x1e1e1e,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.25 },
        sound: {
            shoot: "glock_01",
            reload: "glock_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "glock_switch_01",
        },
    }

// ---- hk416  (M416) - icon changed in v0.2.2
    hk416: {
        name: "M416",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "556mm",
        ammoSpawnCount: 90,
        maxClip: 30,
        maxReload: 30,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 2.3,
        fireDelay: 0.075,
        switchDelay: 0.75,
        barrelLength: 2.7,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 8,
        shotSpread: 4,
        bulletCount: 1,
        bulletType: "bullet_hk416",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-hk416.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.52 },
            tint: 0xdbc49a,
            leftHandOffset: { x: 4.2, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.4 },
        sound: {
            shoot: "hk416_01",
            reload: "hk416_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "hk416_switch_01",
        },
    }

// ---- mac10  (MAC-10) - icon changed in v0.2.2
    mac10: {
        name: "MAC-10",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 96,
        maxClip: 32,
        maxReload: 32,
        extendedClip: 50,
        extendedReload: 50,
        reloadTime: 1.8,
        fireDelay: 0.045,
        switchDelay: 0.75,
        barrelLength: 2.45,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 11,
        shotSpread: 10,
        bulletCount: 1,
        bulletType: "bullet_mac10",
        bulletTypeBonus: "bullet_mac10_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-mac10.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.44 },
            tint: 0x383838,
            leftHandOffset: { x: 1.4, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.35 },
        sound: {
            shoot: "mac10_01",
            reload: "mac10_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "mac10_switch_01",
        },
    }

// ---- mp5  (MP5) - icon changed in v0.2.2
    mp5: {
        name: "MP5",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 90,
        maxClip: 30,
        maxReload: 30,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 2,
        fireDelay: 0.09,
        switchDelay: 0.75,
        barrelLength: 2.625,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 4,
        shotSpread: 3,
        bulletCount: 1,
        bulletType: "bullet_mp5",
        bulletTypeBonus: "bullet_mp5_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-mp5.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.49 },
            tint: 0x121212,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.375 },
        sound: {
            shoot: "mp5_01",
            reload: "mp5_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "mp5_switch_01",
        },
    }

// ---- ot38  (OT-38) - icon changed in v0.2.2
    ot38: {
        name: "OT-38",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "reload",
        ammo: "762mm",
        ammoSpawnCount: 20,
        dualWieldType: "ot38_dual",
        pistol: true,
        maxClip: 5,
        maxReload: 5,
        extendedClip: 5,
        extendedReload: 5,
        reloadTime: 2,
        fireDelay: 0.4,
        switchDelay: 0.3,
        barrelLength: 2.05,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.25,
        bulletCount: 1,
        bulletType: "bullet_ot38",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-ot38.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.4625 },
            tint: 7368816,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "ot38_01",
            reload: "ot38_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "ot38_switch_01",
        },
    }

// ---- ump9  (UMP9) - icon changed in v0.2.2
    ump9: {
        name: "UMP9",
        type: "gun",
        quality: 0,
        fireMode: "burst",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 90,
        maxClip: 30,
        maxReload: 30,
        extendedClip: 40,
        extendedReload: 40,
        reloadTime: 1.9,
        fireDelay: 0.35,
        burstDelay: 0.07,
        switchDelay: 0.75,
        barrelLength: 2.7,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 1.5,
        bulletCount: 1,
        burstCount: 3,
        bulletType: "bullet_ump9",
        bulletTypeBonus: "bullet_ump9_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-ump9.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-med-01.img",
            scale: { x: 0.5, y: 0.515 },
            tint: 0x121212,
            leftHandOffset: { x: 5.6, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.4 },
        sound: {
            shoot: "ump9_01",
            reload: "ump9_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "ump9_switch_01",
        },
    }

// ---- glock_dual  (Dual G18C) - icon changed in v0.2.2
    glock_dual: {
        name: "Dual G18C",
        type: "gun",
        quality: 0,
        fireMode: "auto",
        caseTiming: "shoot",
        ammo: "9mm",
        ammoSpawnCount: 51,
        isDual: true,
        pistol: true,
        maxClip: 34,
        maxReload: 34,
        extendedClip: 62,
        extendedReload: 62,
        reloadTime: 3.8,
        fireDelay: 0.03,
        switchDelay: 0.25,
        barrelLength: 2.2,
        barrelOffset: 0,
        dualOffset: 0.6,
        recoilTime: 1e10,
        moveSpread: 16,
        shotSpread: 18,
        bulletCount: 1,
        bulletType: "bullet_glock",
        bulletTypeBonus: "bullet_glock_bonus",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-glock-dual.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.49 },
            tint: 0x1e1e1e,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.25 },
        sound: {
            shoot: "glock_01",
            reload: "glock_reload_02",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "glock_switch_01",
        },
    }

// ---- ot38_dual  (Dual OT-38) - icon changed in v0.2.2
    ot38_dual: {
        name: "Dual OT-38",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "reload",
        ammo: "762mm",
        ammoSpawnCount: 20,
        isDual: true,
        pistol: true,
        maxClip: 10,
        maxReload: 10,
        extendedClip: 10,
        extendedReload: 10,
        reloadTime: 3.8,
        fireDelay: 0.2,
        switchDelay: 0.3,
        barrelLength: 2,
        barrelOffset: 0,
        dualOffset: 0.6,
        recoilTime: 1e10,
        moveSpread: 4,
        shotSpread: 1.75,
        bulletCount: 1,
        bulletType: "bullet_ot38",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-ot38-dual.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-short-01.img",
            scale: { x: 0.5, y: 0.4625 },
            tint: 0x707070,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "ot38_01",
            reload: "ot38_reload_02",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "ot38_switch_01",
        },
    }

// ---- ots38  (OTs-38) - icon changed in v0.2.2
    ots38: {
        name: "OTs-38",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "reload",
        ammo: "762mm",
        ammoSpawnCount: 20,
        dualWieldType: "ots38_dual",
        pistol: true,
        maxClip: 5,
        maxReload: 5,
        extendedClip: 5,
        extendedReload: 5,
        reloadTime: 2,
        fireDelay: 0.36,
        switchDelay: 0.3,
        barrelLength: 2.05,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 2.4,
        shotSpread: 1.2,
        bulletCount: 1,
        bulletType: "bullet_ots38",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-ots38.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-ots38-01.img",
            scale: { x: 0.5, y: 0.5 },
            tint: 0xffffff,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "ots38_01",
            reload: "ot38_reload_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "ot38_switch_01",
        },
    }

// ---- ots38_dual  (Dual OTs-38) - icon changed in v0.2.2
    ots38_dual: {
        name: "Dual OTs-38",
        type: "gun",
        quality: 1,
        fireMode: "single",
        caseTiming: "reload",
        ammo: "762mm",
        ammoSpawnCount: 40,
        isDual: true,
        pistol: true,
        maxClip: 10,
        maxReload: 10,
        extendedClip: 10,
        extendedReload: 10,
        reloadTime: 3.8,
        fireDelay: 0.18,
        switchDelay: 0.3,
        barrelLength: 2,
        barrelOffset: 0,
        dualOffset: 0.6,
        recoilTime: 1e10,
        moveSpread: 2.8,
        shotSpread: 1.4,
        bulletCount: 1,
        bulletType: "bullet_ots38",
        headshotMult: 2,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-ots38-dual.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-ots38-01.img",
            scale: { x: 0.5, y: 0.5 },
            tint: 0xffffff,
            leftHandOffset: { x: 0, y: 0 },
            recoil: 1,
        },
        particle: { shellScale: 1, shellOffset: 0.225 },
        sound: {
            shoot: "ots38_01",
            reload: "ot38_reload_02",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "ot38_switch_01",
        },
    }

// ---- spas12  (SPAS-12) - sprite changed in v0.3.0
    spas12: {
        name: "SPAS-12",
        type: "gun",
        quality: 0,
        fireMode: "single",
        caseTiming: "shoot",
        ammo: "12gauge",
        deployGroup: 1,
        ammoSpawnCount: 18,
        maxClip: 9,
        maxReload: 1,
        extendedClip: 12,
        extendedReload: 1,
        reloadTime: 0.55,
        fireDelay: 0.75,
        switchDelay: 0.75,
        pullDelay: 0.75,
        barrelLength: 2.8,
        barrelOffset: 0,
        recoilTime: 1e10,
        moveSpread: 3,
        shotSpread: 4,
        bulletCount: 9,
        jitter: 0.2,
        bulletType: "bullet_flechette",
        headshotMult: 1.5,
        speed: { equip: 0, attack: 0 },
        lootImg: {
            sprite: "loot-weapon-spas12.img",
            tint: 0xff00,
            border: "loot-circle-outer-01.img",
            borderTint: 0,
            scale: 0.3,
        },
        worldImg: {
            sprite: "gun-long-01.img",
            scale: { x: 0.5, y: 0.4 },
            tint: 0x2d4251,
            leftHandOffset: { x: 4.9, y: 0 },
            recoil: 1.33,
        },
        particle: { shellScale: 1, shellOffset: 0.45 },
        sound: {
            shoot: "spas12_01",
            reload: "spas12_reload_01",
            cycle: "spas12_cycle_01",
            pull: "spas12_pull_01",
            pickup: "gun_pickup_01",
            empty: "empty_fire_01",
            deploy: "spas12_cycle_01",
        },
    }

